// Generated by `wrangler types` once Cloudflare bindings are configured.
// Kept intentionally minimal so typechecking does not require remote resources.
interface CloudflareEnv {
  DB: D1Database;
  MEDIA: R2Bucket;
  NEXT_PUBLIC_SITE_URL: string;
}
